version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.10
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: tantor.db.elephantsql.com
            port: '5432'
            database: lywbzeco
            schema: plants
            user: lywbzeco
            password: OfbSSuELi0PudlxcgcJ4vzXgBElwpi_4
            migrations: true